site_name: Okyen Source Software
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search
  - blog:
      blog_dir: "blog"
      blog_url: "blog"
      blog_page_title: "Blog"
      blog_description: "Software-related insights and articles"
      draft_indicator: true
  - rss:
      feed_title: "Okyen Source Software Blog"
      feed_description: "Stay updated with the latest blog posts on Okyen Source Software."
      feed_url: "https://mokyen.github.io/okyensourcesoftware"
      length: 10

extra_javascript:
  - https://giscus.app/client.js

<script src="https://giscus.app/client.js"
        data-repo="mokyen/okyensourcesoftware"
        data-repo-id="R_kgDOK-mjQw"
        data-category="Blog Comments"
        data-category-id="DIC_kwDOK-mjQ84Cl7Cj"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="preferred_color_scheme"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>

nav:
  - Home: 'index.md'
  - About:
      - 'about.md'
      - 'bio.md'
  - Blog:
      - 'blog/_index.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/mokyen" target="_blank" rel="noopener">Michael Okyen</a>
