site_name: Okyen Source Software
site_url: https://www.okyensourcesoftware.com
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
plugins:
  - search
  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"
      post_url_format: "{slug}"
      blog_toc: true
      blog_description: "Software-related insights and articles"
      draft_indicator: true
      authors:
        - name: Michael Okyen
          description: Software Engineer
          url: https://github.com/mokyen
  - rss:
      feed_title: "Okyen Source Software Blog"
      feed_description: "Stay updated with the latest blog posts on Okyen Source Software."
      feed_url: "https://mokyen.github.io/okyensourcesoftware"
      length: 10
      authors:
        - name: Michael Okyen
          url: https://github.com/mokyen
extra_javascript:
  - https://giscus.app/client.js
extra:
  giscus:
    repo: "mokyen/okyensourcesoftware"
    repo_id: "R_kgDOK-mjQw"
    category: "Blog Comments"
    category_id: "DIC_kwDOK-mjQ84Cl7Cj"
    mapping: "pathname"
    strict: "0"
    reactions_enabled: "1"
    emit_metadata: "0"
    input_position: "top"
    theme: "preferred_color_scheme"
    lang: "en"
    loading: "lazy"
nav:
  - Home: 'index.md'
  - About:
      - 'about.md'
      - 'bio.md'
  - Blog:
      - 'blog/_index.md'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: |
  &copy; 2024 <a href="https://github.com/mokyen" target="_blank" rel="noopener">Michael Okyen</a>
