name: ci

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensuring full git history

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Build the site
      - name: Build the site
        run: mkdocs build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
