name: Deploy Preview
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-blogging-plugin mkdocs-rss-plugin pillow cairosvg
      
      # Step 4: Update site_url for Preview
      - name: Update site_url for Preview
        run: |
          if grep -q "site_url:" mkdocs.yml; then
            sed -i "s|site_url: .*|site_url: https://mokyen.github.io/okyensourcesoftware/preview-${{ github.event.number }}|" mkdocs.yml
          else
            echo "site_url: https://mokyen.github.io/okyensourcesoftware/preview-${{ github.event.number }}" >> mkdocs.yml
          fi
      
      # Step 5: Build the site
      - name: Build the site
        run: mkdocs build
      
      # Step 6: Check if Preview Branch Exists
      - name: Check if Preview Branch Exists
        id: check_branch
        run: |
          git fetch --all
          if git ls-remote --heads origin "preview-${{ github.event.number }}"; then
            echo "Branch exists"
            echo "branch_exists=true" >> $GITHUB_ENV
          else
            echo "Branch does not exist"
            echo "branch_exists=false" >> $GITHUB_ENV
          fi
      
      # Step 7: Deploy to GitHub Pages (New Branch)
      - name: Deploy to GitHub Pages (Preview - New Branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: preview-${{ github.event.number }}
          cname: "" # Explicitly set no CNAME
          force_orphan: true # Creates a new orphan branch without history
        if: env.branch_exists == 'false'
      
      # Step 8: Update Existing Preview Branch
      - name: Update Existing Preview Branch
        if: env.branch_exists == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Fetch all branches
          git fetch --all
          
          # Create and switch to a temporary branch
          git checkout -b temp-preview-branch
          
          # Remove CNAME file if it exists
          rm -f CNAME || true
          
          # Copy the new site contents
          cp -r ./site/* .
          
          # Stage changes
          git add .
          
          # Create commit
          git commit -m "Update Preview Branch for PR #${{ github.event.number }}"
          
          # Force push to the preview branch
          git push origin temp-preview-branch:preview-${{ github.event.number }} -f
      
      # Step 9: Display Preview Site URL
      - name: Display Preview Site URL
        run: |
          echo "Preview Site URL: https://mokyen.github.io/okyensourcesoftware/preview-${{ github.event.number }}/"
