name: Deploy Preview

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-blogging-plugin mkdocs-rss-plugin pillow cairosvg

      # Step 4: Dynamically update site_url for Preview
      - name: Update site_url for Preview
        run: |
          sed -i "s|site_url: .*|site_url: https://mokyen.github.io/okyensourcesoftware/gh-pages-preview/${{ github.event.number }}/|" mkdocs.yml

      # Step 5: Build the site
      - name: Build the site
        run: mkdocs build

      # Step 6: Check if Preview Branch Exists
      - name: Check if Preview Branch Exists
        id: check_branch
        run: |
          if git ls-remote --heads origin gh-pages-preview/${{ github.event.number }}; then
            echo "branch_exists=true" >> $GITHUB_ENV
          else
            echo "branch_exists=false" >> $GITHUB_ENV
          fi

      # Step 7: Deploy to GitHub Pages (Preview)
      - name: Deploy to GitHub Pages (Preview)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages-preview/${{ github.event.number }}
          keep_files: true
        if: env.branch_exists == 'false'

      - name: Update Existing Preview Branch
        if: env.branch_exists == 'true'
        run: |
          git fetch origin gh-pages-preview/${{ github.event.number }}
          git checkout gh-pages-preview/${{ github.event.number }}
          cp -r ./site/* .
          git add .
          git commit -m "Update Preview Branch for PR #${{ github.event.number }}"
          git push origin gh-pages-preview/${{ github.event.number }}

      # Step 8: Print Preview Site URL
      - name: Display Preview Site URL
        run: echo "Preview Site URL: https://mokyen.github.io/okyensourcesoftware/gh-pages-preview/${{ github.event.number }}/"
